//------------------------------------------------------------------------------
// <auto-generated>
//  Last update:  Wednesday, 2 January 2019 3:43 PM
//  T4 template:  ControllerNames.tt
//  How to trigger: Goto Properties -> Custom Tool -> rename from TextTemplatingFileGeneratorr to TextTemplatingFileGenerator
//  How to disable: Rename from TextTemplatingFileGenerator back to TextTemplatingFileGeneratorr
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenderSearch.Contracts.Infrastructure
{
    public static class ControllerNames
    {
        public const string Home = "Home";
        public const string Lookup = "Lookup";
        public const string AspNetUser = "AspNetUser";
        public const string AspNetUserRole = "AspNetUserRole";
        public const string Address = "Address";
        public const string Company = "Company";
        public const string Contract = "Contract";
        public const string Dependent = "Dependent";
        public const string Employee = "Employee";
        public const string Account = "Account";
        public const string Dashboard = "Dashboard";
        public const string Manage = "Manage";
    }
}
