//------------------------------------------------------------------------------
// <auto-generated>
//  Last update:  Tuesday, 11 December 2018 8:01 PM
//  T4 template:  ControllerNames.tt
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenderSearch.Contracts.Infrastructure
{
    public static class ControllerNames
    {
        public const string Home = "Home";
        public const string Lookup = "Lookup";
        public const string AspNetUser = "AspNetUser";
        public const string AspNetUserRole = "AspNetUserRole";
        public const string Address = "Address";
        public const string Company = "Company";
        public const string Contract = "Contract";
        public const string Dependent = "Dependent";
        public const string Employee = "Employee";
        public const string Account = "Account";
        public const string Dashboard = "Dashboard";
        public const string Manage = "Manage";
    }
}
