//------------------------------------------------------------------------------
// <auto-generated>
//  Date updated:  Wednesday, 2 January 2019 3:46 PM
//  Template:  LookupTableEnums.tt
//  How to trigger: Goto Properties -> Custom Tool -> rename from TextTemplatingFileGeneratorr to TextTemplatingFileGenerator
//  How to disable: Rename from TextTemplatingFileGenerator back to TextTemplatingFileGeneratorr
// </auto-generated>
//------------------------------------------------------------------------------
namespace TenderSearch.Web.Infrastructure
{
	public static class LookupGroups
	{
		public const string AddressOwnerType = "AddressOwnerType";
		public const string AddressType = "AddressType";
		public const string CategoryType = "CategoryType";
		public const string ContractType = "ContractType";
		public const string Department = "Department";
		public const string Dependent = "Dependent";
		public const string EmployeeStatusType = "EmployeeStatusType";
		public const string Gender = "Gender";
		public const string MaritalStatus = "MaritalStatus";
		public const string PositionTitle = "PositionTitle";
		public const string RankType = "RankType";
		public const string Salutation = "Salutation";
	}

	public enum eAddressOwnerType
	{
	    Employee = 1,
	    Dependent = 2,
	    Education = 3,
	    Office = 4,
	    Business = 5
	}

	public enum eAddressType
	{
	    Home = 1,
	    Office = 2,
	    Business = 3
	}

	public enum eCategoryType
	{
	    Associate = 1,
	    Member = 2,
	    Other = 3,
	    Savers = 4
	}

	public enum eContractType
	{
	    Standardcontract = 1,
	    Mastercontact = 2
	}

	public enum eDepartment
	{
	    Department01 = 1,
	    Department02 = 2,
	    Department03 = 3,
	    Department04 = 4
	}

	public enum eDependent
	{
	    Son = 1,
	    Daugther = 2,
	    Husband = 3,
	    Wife = 4,
	    Father = 5,
	    Mother = 6,
	    Brother = 7,
	    Sister = 8
	}

	public enum eEmployeeStatusType
	{
	    Active = 1,
	    Pension = 2,
	    Survivor = 3
	}

	public enum eGender
	{
	    Male = 1,
	    Female = 2
	}

	public enum eMaritalStatus
	{
	    Single = 1,
	    Married = 2,
	    Widowed = 3,
	    Separated = 4,
	    LegallySeparated = 5
	}

	public enum ePositionTitle
	{
	    AccountsOfficer = 1,
	    Administrator = 2,
	    ASST = 3,
	    Audit = 4,
	    Bookkeeper = 5,
	    CAPCONOfficer = 6,
	    DataExtractor = 7,
	    Extension = 8,
	    ExtraUser = 9,
	    GeneralClerk = 10,
	    IT = 11,
	    LoanOfficer = 12,
	    LoanStaff = 13,
	    ManagerCEO = 14,
	    MgtInfoSpecialist = 15,
	    Officer = 16,
	    PITTS = 17,
	    SalesClerk = 18,
	    System = 19,
	    SystemEngineer = 20,
	    Treasurer = 21,
	    User = 22,
	    Utility = 23
	}

	public enum eRankType
	{
	    NONE = 1,
	    CIV = 2,
	    JO1 = 3,
	    JO2 = 4,
	    JO3 = 5,
	    INSP = 6,
	    SINSP = 7,
	    SJO1 = 8,
	    SJO2 = 9,
	    SJO3 = 10,
	    CSUPT = 11,
	    SJO4 = 12,
	    SSUPT = 13,
	    SUPT = 14,
	    DIR = 15,
	    CINSP = 16
	}

	public enum eSalutation
	{
	    Mr = 1,
	    Mrs = 2
	}
}
