// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace TenderSearch.DataMigration.SqlServerMigrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SeedContactPersons : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeedContactPersons));
        
        string IMigrationMetadata.Id
        {
            get { return "201806260158486_SeedContactPersons"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
