//------------------------------------------------------------------------------
// <auto-generated>
//  Last update:  Wednesday, 2 January 2019 3:46 PM
//  T4 template:  TenderSearchDb.tt
//  How to trigger: Goto Properties -> Custom Tool -> rename from TextTemplatingFileGeneratorr to TextTemplatingFileGenerator
//  How to disable: Rename from TextTemplatingFileGenerator back to TextTemplatingFileGeneratorr
// </auto-generated>
//------------------------------------------------------------------------------
using TenderSearch.Business.Common.Entities;
using System.Data.Entity;

namespace TenderSearch.Data
{
    public class TenderSearchDb : ApplicationDbContext
    {
        public TenderSearchDb()
        {
            Configuration.ProxyCreationEnabled = false;
        }

        public DbSet<Address> Addresses { get; set; }

        public DbSet<Barangay> Barangays { get; set; }

        public DbSet<CityMunicipality> CityMunicipalities { get; set; }

        public DbSet<Company> Companies { get; set; }

        public DbSet<Contract> Contracts { get; set; }

        public DbSet<Dependent> Dependents { get; set; }

        public DbSet<Employee> Employees { get; set; }

        public DbSet<Lookup> Lookups { get; set; }

        public DbSet<Province> Provinces { get; set; }

        public DbSet<Region> Regions { get; set; }
    }
}
