//------------------------------------------------------------------------------
// <auto-generated>
//  Last update:  Tuesday, 11 December 2018 7:34 PM
//  T4 template:  TenderSearchDb.tt
// </auto-generated>
//------------------------------------------------------------------------------
using TenderSearch.Business.Common.Entities;
using System.Data.Entity;

namespace TenderSearch.Data
{
    public class TenderSearchDb : ApplicationDbContext
    {
        public DbSet<Address> Addresses { get; set; }

        public DbSet<Barangay> Barangays { get; set; }

        public DbSet<CityMunicipality> CityMunicipalities { get; set; }

        public DbSet<Company> Companies { get; set; }

        public DbSet<Contract> Contracts { get; set; }

        public DbSet<Dependent> Dependents { get; set; }

        public DbSet<Employee> Employees { get; set; }

        public DbSet<Lookup> Lookups { get; set; }

        public DbSet<Province> Provinces { get; set; }

        public DbSet<Region> Regions { get; set; }
    }
}
