// <auto-generated />
namespace TenderSearch.DataMigration.SqlServerMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SeedAspNetUsers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeedAspNetUsers));
        
        string IMigrationMetadata.Id
        {
            get { return "201812191921345_SeedAspNetUsers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
