//------------------------------------------------------------------------------
// <auto-generated>
//  Date updated:  Wednesday, 2 January 2019 3:48 PM
//  Template:  EntitySortableFieldEnums.tt
//  * Enum members are arranged from top to bottom, the same order it was declared.
//  * Or use SortOrder attribute into your property.
//  How to trigger: Goto Properties -> Custom Tool -> rename from TextTemplatingFileGeneratorr to TextTemplatingFileGenerator
//  How to disable: Rename from TextTemplatingFileGenerator back to TextTemplatingFileGeneratorr
// </auto-generated>
//------------------------------------------------------------------------------
namespace TenderSearch.Business.Common.Entities
{
    public enum eAddress
    {
        StreetAddress,
        OwnerType,
        AddressType
    }

    public enum eCityMunicipality
    {
        Name,
        ZipCode
    }

    public enum eCompany
    {
        Name,
        Description,
        Website,
        AbnCan
    }

    public enum eContract
    {
        ContractType,
        DateSigned,
        EndDate,
        RenewalDate,
        Price
    }

    public enum eDependent
    {
        FirstName,
        LastName,
        MiddleName,
        DisplayName,
        BirthDate,
        Gender,
        Relationship,
        CivilStatus
    }

    public enum eEmployee
    {
        FirstName,
        LastName,
        MiddleName,
        DisplayName,
        BirthDate,
        Gender,
        EmployeeNumber,
        AtmNumber,
        SssNumber,
        TinNumber,
        PhilHealthNumber,
        PagIbigNumber,
        PassportNumber,
        DepartmentName,
        MembershipDate,
        HiredDate,
        EmploymentEndDate,
        CivilStatus
    }

    public enum eLookup
    {
        Group,
        SubGroup,
        Value,
        Text
    }

}
